version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: starchaos
    ports:
      - "5432:5432"
    networks:
      - flask_network

  flaskapp:
    build:
      context: .
    restart: always
    depends_on:
      - db
    volumes:
      - app-data:/app/app_data
    env_file:
      - ./starchaos/.env
    networks:
      flask_network:
        aliases:
          - flaskapp
    environment:
      - FLASK_APP=run.py
    command: flask run --host=0.0.0.0
    ports:
      - "80:5000"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskapp
    networks:
      - flask_network

networks:
  flask_network:

volumes:
  db-data:
  app-data:
